loja/urls.py
from django.contrib import admin  # type:ignore
from django.urls import path, include  # type:ignore
from django.conf import settings  # type:ignore
from django.conf.urls.static import static  # type:ignore


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('pagar/', include('pagamento.urls'))
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

pagamento/urls.py
from django.urls import path  # type:ignore

from pagamento import views


app_name = 'pagamento'

urlpatterns = [
    path('inicio/<int:pk>', views.inicio, name='inicio'),
    path(
        'controle-pagamento/<int:pk>/credito',
        views.cartao_cred,
        name='credito'
    ),
    path(
        'controle-pagamento/<int:pk>/boleto',
        views.boleto,
        name='boleto'
    ),
    path(
        'controle-pagamento/<int:pk>/pix',
        views.pix,
        name='pix'
    ),
]

pagamento/models.py
from django.db import models

# Create your models here.

pagamento/views.py
import json
import requests

import pytz

from datetime import timedelta, datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from pedido.models import Pedido
from perfil.models import Perfil


# funcao aux para publickey
def get_public_key():
    url = 'https://sandbox.api.pagseguro.com/public-keys/'
    headers = {
        "accept": "application/json",
        "Authorization": "Bearer E0A4D184FD684D5D9036F8DE1C7DBE34",
        "content-type": "application/json"
    }
    body = json.dumps({
        "type": "card"
    })
    reqs = requests.post(url, headers=headers, data=body)
    return reqs.json()['public_key']


# funcao que renderiza uma pagina para "confirmar o pagamento"
@login_required
def inicio(request, pk):
    pedido = get_object_or_404(Pedido, pk=pk)
    # Se o parâmetro não estiver presente, o método de pagamento
    # padrão será 'Cartao'
    metodo_pagamento = request.GET.get('metodo_pagamento', 'Cartao')

    data = {
        'public_key': get_public_key(),
        'pedido': pedido,
        'pagamento': metodo_pagamento
    }
    return render(
        request,
        'pagamento/pagamento.html',
        data
    )


# ///////////////////////////////////////// #
# !! VIEWS PARA CRIAR ORDEM DE PAGAMENTO !! #
# funcao para solicitar a ordem de serviço do pagseguro com cartao de cred
@login_required
def cartao_cred(request, pk):
    # pegando o pedido
    pedido = get_object_or_404(Pedido, pk=pk)
    # pegando item pedido
    item_pedido = pedido.itempedido_set.all()

    # como item_pedido sera uma lista
    # é feito um for para passar os valores para dentro de variaveis
    for item in item_pedido:
        # conferindo se o nome do item é menor que 100 chars
        # pois é o limite do pagseguro
        if len(item.produto) > 100:
            nome_produto = item.produto[:99]
        else:
            nome_produto = item.produto

        qtd = item.quantidade
        # checando se tem preço promocional no item
        if item.preco_promocional:
            valor_item = item.preco_promocional
        else:
            valor_item = item.preco

    # pegando o cliente
    cliente = Perfil.objects.get(user=request.user)

    # Aqui obtem os dados do formulário do request.POST
    # do cartão de credito
    card_holder = request.POST.get('cardHolder')
    card_cvv = request.POST.get('cardCvv')
    encrypted_card = request.POST.get('encriptedCard')

    # separando os dados do cliente
    if cliente.user.first_name:
        cliente_nome = cliente.user.first_name
    else:
        cliente_nome = cliente.user.username

    cliente_email = cliente.user.email
    cliente_cpf = cliente.cpf

    # iniciando a integração com a API do pagseguro
    url = 'https://sandbox.api.pagseguro.com/orders/'
    headers = {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer E0A4D184FD684D5D9036F8DE1C7DBE34'
    }
    # corpo de envio para API do pagseguro
    body = json.dumps({
        "reference_id": str(pedido.id),
        "customer": {
            "name": cliente_nome,
            "email": cliente_email,
            "tax_id": cliente_cpf,
        },
        "items": [
            {
                "reference_id": str(pedido.id),
                "name": nome_produto,
                "quantity": qtd,
                "unit_amount": int(valor_item * 100)
            }
        ],
        "shipping": {
            "address": {
                "street": cliente.endereco,
                "number": cliente.numero,
                "complement": cliente.complemento,
                "locality": cliente.bairro,
                "city": cliente.cidade,
                "region_code": cliente.estado,
                "country": "BRA",
                "postal_code": cliente.cep
            }
        },
        "notification_urls": [
            "https://meusite.com/notificacoes"
        ],
        "charges": [
            {
                "reference_id": f"Pedido {str(pedido.id)}",
                "description": "descricao da cobranca",
                "amount": {
                    "value": int(pedido.total * 100),
                    "currency": "BRL"
                },
                "payment_method": {
                    'soft_descriptor': 'Just a E-Commerce',
                    "type": "CREDIT_CARD",
                    "installments": 1,
                    "capture": True,
                    "card": {
                        "encrypted": encrypted_card,
                        "security_code": card_cvv,
                        "holder": {
                            "name": card_holder
                        },
                        "store": True
                    }
                }
            }
        ]
    })
    reqs = requests.post(url, headers=headers, data=body)
    if reqs.status_code == 201:
        pedido.status = 'Aprovado'
        pedido.save()

        ordem_id = reqs.json()['id']
        contexto = {
            'ordem_id': ordem_id,
            'pedido': pedido,
            'pagamento': 'CREDIT_CARD'
        }
        return render(
            request,
            'pagamento/status_compra.html',
            contexto
        )
    else:
        return render(request, 'pagamento/error_pagamento.html')


# funcao para solicitar a ordem de serviço do pagseguro com boleto
@login_required
def boleto(request, pk):
    # pegando a data de hoje para calcular vencimento do boleto.
    hoje = timezone.now().date()
    vencimento = hoje + timedelta(days=5)
    # pegando o pedido
    pedido = get_object_or_404(Pedido, pk=pk)
    # pegando item pedido
    item_pedido = pedido.itempedido_set.all()

    # como item_pedido sera uma lista
    # é feito um for para passar os valores para dentro de variaveis
    for item in item_pedido:
        # conferindo se o nome do item é menor que 100 chars
        # pois é o limite do pagseguro
        if len(item.produto) > 100:
            nome_produto = item.produto[:99]
        else:
            nome_produto = item.produto

        qtd = item.quantidade
        # checando se tem preço promocional no item
        if item.preco_promocional:
            valor_item = item.preco_promocional
        else:
            valor_item = item.preco

    # pegando o cliente
    cliente = Perfil.objects.get(user=request.user)

    # separando os dados do cliente
    if cliente.user.first_name:
        cliente_nome = cliente.user.first_name
    else:
        cliente_nome = cliente.user.username

    cliente_email = cliente.user.email
    cliente_cpf = cliente.cpf

    # pegando valor total para calcular desconto com boleto.
    valor_total = pedido.total * 100
    # desconto de 10% a vista no boleto.
    disconto_boleto_total = valor_total - (valor_total * 0.1)

    url = 'https://sandbox.api.pagseguro.com/orders'
    headers = {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
        'Authorization': 'Bearer E0A4D184FD684D5D9036F8DE1C7DBE34'
    }

    body = json.dumps({
        "reference_id": str(pedido.id),
        "customer": {
            "name": cliente_nome,
            "email": cliente_email,
            "tax_id": cliente_cpf,
        },
        "items": [
            {
                "reference_id": str(pedido.id),
                "name": nome_produto,
                "quantity": qtd,
                "unit_amount": int(valor_item * 100)
            }
        ],
        "shipping": {
            "address": {
                "street": cliente.endereco,
                "number": cliente.numero,
                "complement": cliente.complemento,
                "locality": cliente.bairro,
                "city": cliente.cidade,
                "region_code": cliente.estado,
                "country": "BRA",
                "postal_code": cliente.cep
            }
        },
        "notification_urls": [
            "https://meusite.com/notificacoes"
        ],
        "charges": [
            {
                "reference_id": str(pedido.id),
                "description": "descricao da cobranca",
                "amount": {
                    "value": int(disconto_boleto_total),
                    "currency": "BRL"
                },
                "payment_method": {
                    "type": "BOLETO",
                    "boleto": {
                        "due_date": str(vencimento),
                        "instruction_lines": {
                            "line_1": "Pagamento processado para DESC Fatura",
                            "line_2": "Via PagSeguro"
                        },
                        "holder": {
                            "name": cliente_nome,
                            "tax_id": cliente_cpf,
                            "email": cliente_email,
                            "address": {
                                "country": "Brasil",
                                "region": cliente.estado,
                                "region_code": cliente.estado,
                                "city": cliente.cidade,
                                "postal_code": cliente.cep,
                                "street": cliente.endereco,
                                "number": cliente.numero,
                                "locality": cliente.bairro
                            }
                        }
                    }
                }
            }
        ]
    })
    reqs = requests.post(url, headers=headers, data=body)
    if reqs.status_code == 201:
        pedido.status = 'Aprovado'
        pedido.save()

        ordem_id = reqs.json()['id']

        link_boleto_pdf = None

        for charge in reqs.json()['charges']:
            if 'links' in charge:
                for link in charge['links']:
                    if link['media'] == 'application/pdf':
                        link_boleto_pdf = link['href']
                        break
                if link_boleto_pdf:

pagamento/templates/pagamento/boleto.html
{% extends "base.html" %}
{% load filtros %}
{% load static %}

{% block conteudo %}
    <h2 class="text-center mb-5 mt-4">Confirme sua compra</h2>
    <hr>
    {% include 'parciais/_pedido.html' %}
    <hr>

    <script src="https://assets.pagseguro.com.br/checkout-sdk-js/rc/dist/browser/pagseguro.min.js"></script>
    <script src="{% static 'assets/custom/js/pag.js' %}"></script>

{% endblock %}

pagamento/templates/pagamento/error_pagamento.html
{% extends "base.html" %}

{% load filtros %}
{% load static %}

{% block conteudo %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header text-center bg-warning text-white">
                        <h3>Houve um erro com o pagamento</h3>
                    </div>
                    <div class="card-body">
                        <p class="text-center">
                            Infelizmente, não foi possível processar o pagamento neste momento. Por favor, tente novamente mais tarde.
                        </p>
                        <p class="text-center">
                            Se o problema persistir, entre em contato conosco.
                        </p>
                        <div class="text-center">
                            <a href="#" class="btn btn-primary">Entre em Contato</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock conteudo %}

pagamento/templates/pagamento/pagamento.html
{% extends "base.html" %}
{% load filtros %}
{% load static %}

{% block conteudo %}
{% if pagamento == 'Cartao' %}
    <h2 class="text-center mb-5 mt-4">Confirme sua compra</h2>
    <hr>
    {% include 'parciais/_pedido.html' %}
    <hr>
        <div id="cartaoCreditoForm">
            <h2 class="text-center mb-5 mt-5">Preencha com os dados do cartão de crédito</h2>
            <form method="post" name="formCard" id="formCard" action="{% url "pagamento:credito" pedido.id %}">
                {% csrf_token %}
                <div class="col-6 m-auto">
                    <input type="text" name="publicKey" id="publicKey" value="{{ public_key }}" hidden="true">
                    <input type="text" name="encriptedCard" id="encriptedCard" hidden="true">
                    <input type="text" class="form-control mb-3" name="cardNumber" id="cardNumber" maxlength="16" placeholder="Número do Cartão">
                    <input type="text" class="form-control mb-3" name="cardHolder" id="cardHolder" placeholder="Nome no Cartão">
                    <input type="text" class="form-control mb-3" name="cardMonth" id="cardMonth" maxlength="2" placeholder="Mês de Validade do Cartão">
                    <input type="text" class="form-control mb-3" name="cardYear" id="cardYear" maxlength="4" placeholder="Ano do Cartão">
                    <input type="text" class="form-control mb-3" name="cardCvv" id="cardCvv" maxlength="4" placeholder="CVV do Cartão">
                    <input type="submit" class="btn btn-primary btn-block btn-lg" value="Pagar">
                </div>
            </form>
        </div>
{% elif pagamento == 'Boleto' %}
    <h2 class="text-center mb-5 mt-4">Confirme sua compra</h2>
    <hr>
    {% include 'parciais/_pedido.html' %}
    <hr>
    <h2 class="text-center mb-5 mt-5"></h2>
    <a href="{% url 'pagamento:boleto' pk=pedido.id %}" class="btn btn-primary btn-lg">Clique aqui para confirmar sua compra</a>
{% elif pagamento == 'Pix' %}
    <h2 class="text-center mb-5 mt-4">Confirme sua compra</h2>
    <hr>
    {% include 'parciais/_pedido.html' %}
    <hr>
    <h2 class="text-center mb-5 mt-5"></h2>
    <a href="{% url 'pagamento:pix' pk=pedido.id %}" class="btn btn-primary btn-lg">Clique aqui para confirmar sua compra</a>
{% endif %}

    <script src="https://assets.pagseguro.com.br/checkout-sdk-js/rc/dist/browser/pagseguro.min.js"></script>
    <script src="{% static 'assets/custom/js/pag.js' %}"></script>

{% endblock %}

pagamento/templates/pagamento/status_compra.html
{% extends "base.html" %}

{% load filtros %}
{% load static %}

{% block conteudo %}
    {% include 'parciais/_pedido.html' %}
    <hr>
{% endblock conteudo %}