loja/urls.py
from django.contrib import admin  # type:ignore
from django.urls import path, include  # type:ignore
from django.conf import settings  # type:ignore
from django.conf.urls.static import static  # type:ignore


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('produto.urls')),
    path('perfil/', include('perfil.urls')),
    path('pedido/', include('pedido.urls')),
    path('pagar/', include('pagamento.urls'))
] + static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

pagamento/urls.py
from django.urls import path  # type:ignore

from pagamento import views


app_name = 'pagamento'

urlpatterns = [
    path('inicio/<int:pk>', views.inicio, name='inicio'),
    path(
        'controle-pagamento/<int:pk>/credito',
        views.cartao_cred,
        name='credito'
    ),
    path(
        'controle-pagamento/<int:pk>/boleto',
        views.boleto,
        name='boleto'
    ),
    path(
        'controle-pagamento/<int:pk>/pix',
        views.pix,
        name='pix'
    ),
]

pedido/urls.py
from django.urls import path  # type:ignore
from . import views


app_name = 'pedido'

urlpatterns = [
    path('pagar/<int:pk>', views.Pagar.as_view(), name='pagar'),
    path('salvarpedido/', views.SalvarPedido.as_view(), name='salvarpedido'),
    path('lista/', views.Lista.as_view(), name='lista'),
    path('detalhe/<int:pk>', views.Detalhe.as_view(), name='detalhe'),
]

pedido/models.py
from django.db import models  # type:ignore
from django.contrib.auth.models import User  # type:ignore


class Pedido(models.Model):
    class Meta:
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    STATUS_CHOICES = (
        ('A', 'Aprovado'), ('C', 'Criado'),
        ('R', 'Reprovado'), ('P', 'Pendente'),
        ('E', 'Enviado'), ('F', 'Finalizado'),
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total = models.FloatField()
    qtd_total = models.PositiveIntegerField()
    status = models.CharField(
        default='C',
        max_length=1,
        choices=STATUS_CHOICES
    )

    def __str__(self):
        return f'Pedido N. {self.id}'


class ItemPedido(models.Model):
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
    produto = models.CharField(max_length=255)
    produto_id = models.PositiveIntegerField()
    variacao = models.CharField(max_length=255)
    variacao_id = models.PositiveIntegerField()
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    quantidade = models.PositiveIntegerField()
    imagem = models.CharField(max_length=2000)

    def __str__(self):
        return f'Item do {self.pedido}'

pedido/views.py
from django.shortcuts import redirect, reverse  # type:ignore
from django.views.generic import ListView, DetailView  # type:ignore
from django.views import View  # type:ignore
# from django.http import HttpResponse  # type:ignore
from django.contrib import messages  # type:ignore

from produto.models import Variacao
from .models import Pedido, ItemPedido

from utils import utils


class DispatchLoginRequiredMixin(View):
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:criar')

        return super().dispatch(*args, **kwargs)

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs


class Pagar(DispatchLoginRequiredMixin, DetailView):
    template_name = 'pedido/pagar.html'
    model = Pedido
    pk_url_kwarg = 'pk'
    context_object_name = 'pedido'


class SalvarPedido(View):
    template_name = 'pedido/pagar.html'

    def get(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.error(
                self.request,
                'Você precisa fazer login.'
            )
            return redirect('perfil:criar')

        if not self.request.session.get('carrinho'):
            messages.error(
                self.request,
                'Seu carrinho está vazio.'
            )
            return redirect('produto:lista')

        carrinho = self.request.session.get('carrinho')
        carrinho_variacao_ids = [v for v in carrinho]
        bd_variacoes = list(
            Variacao.objects.select_related('produto')
            .filter(id__in=carrinho_variacao_ids)
        )

        for variacao in bd_variacoes:
            vid = str(variacao.id)

            estoque = variacao.estoque
            qtd_carrinho = carrinho[vid]['quantidade']
            preco_unt = carrinho[vid]['preco_unitario']
            preco_unt_promo = carrinho[vid]['preco_unitario_promocional']

            error_msg_estoque = ''

            if estoque < qtd_carrinho:
                carrinho[vid]['quantidade'] = estoque
                carrinho[vid]['preco_quantitativo'] = estoque * preco_unt
                carrinho[vid]['preco_quantitativo_promocional'] = estoque * \
                    preco_unt_promo

                error_msg_estoque = 'Estoque insuficiente para alguns '\
                    'produtos do seu carrinho. '\
                    'Reduzimos a quantidade desses produtos. Por favor, '\
                    'verifique quais produtos foram afetados a seguir.'

            if error_msg_estoque:
                messages.error(
                    self.request,
                    error_msg_estoque
                )

                self.request.session.save()
                return redirect('produto:carrinho')

        qtd_total_carrinho = utils.cart_total_qtd(carrinho)
        valor_total_carrinho = utils.cart_totals(carrinho)

        pedido = Pedido(
            user=self.request.user,
            total=valor_total_carrinho,
            qtd_total=qtd_total_carrinho,
            status='C',
        )

        pedido.save()

        ItemPedido.objects.bulk_create(
            [
                ItemPedido(
                    pedido=pedido,
                    produto=v['produto_nome'],
                    produto_id=v['produto_id'],
                    variacao=v['variacao_nome'],
                    variacao_id=v['variacao_id'],
                    preco=v['preco_quantitativo'],
                    preco_promocional=v['preco_quantitativo_promocional'],
                    quantidade=v['quantidade'],
                    imagem=v['imagem'],
                ) for v in carrinho.values()
            ]
        )

        del self.request.session['carrinho']

        return redirect(
            reverse(
                'pedido:pagar',
                kwargs={
                    'pk': pedido.pk
                }
            )
        )


class Detalhe(DispatchLoginRequiredMixin, DetailView):
    model = Pedido
    context_object_name = 'pedido'
    template_name = 'pedido/detalhe.html'
    pk_url_kwarg = 'pk'


class Lista(DispatchLoginRequiredMixin, ListView):
    model = Pedido
    context_object_name = 'pedidos'
    template_name = 'pedido/lista.html'
    paginate_by = 10
    ordering = ['-id']

pedido/templates/pedido/detalhe.html
{% extends 'base.html' %}

{% block titulo %}{{ pedido }} | {% endblock %}

{% load filtros %}
{% load static %}

{% block conteudo %}

{% include 'parciais/_pedido.html' %}

{% endblock %}

pedido/templates/pedido/lista.html
{% extends 'base.html' %}
{% load filtros %}

{% block titulo %}Pedidos de {{ user }} | {% endblock %}

{% block conteudo %}

    <div class="row">
        <div class="col">
            <h3 class="mb-4">Pedidos de {{ user }}</h3>
            <p>Abaixo todos os seus pedidos realizados na loja.</p>

            <div class="table-responsive">
                <table class="table table-striped">
                    <tr>
                        <th scope="col">Pedido</th>
                        <th scope="col">Total</th>
                        <th scope="col">Qtd. Itens</th>
                        <th scope="col">Status</th>
                        <th scope="col">Mais detalhes</th>
                    </tr>


                    {% for pedido in pedidos %}
                    <tr>
                        <th scope="row">{{ pedido }}</td>
                        <td>{{ pedido.total|formata_preco }}</td>
                        <td>{{ pedido.qtd_total }}</td>
                        <td>{{ pedido.get_status_display }}</td>
                        <td>
                            <a href="{% url 'pedido:detalhe' pedido.id %}">
                                Ver <i class="fas fa-search-plus ml-2"></i>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}


                </table>
            </div>
        </div>
    </div>

{% include 'parciais/_pagination.html' %}

{% endblock %}

pedido/templates/pedido/pagar.html
{% extends 'base.html' %}

{% block titulo %}Pagamento | {% endblock %}

{% load filtros %}
{% load static %}

{% block conteudo %}
<div class="row">
    <div class="col">
        <div class="container mt-5">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <h2 class="text-left mb-4">Escolha a forma de pagamento</h2>
                            <div class="input-group mb-3">
                                <label class="input-group-text bg-primary text-light" for="paymentMethod">Forma de Pagamento</label>
                                <select class="form-select" id="paymentMethod" aria-label="Seleção de Método de Pagamento">
                                    <option selected>Cartão de crédito</option>
                                    <option value="1">Pix à vista</option>
                                    <option value="2">Boleto bancário à vista</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include 'parciais/_pedido.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" id="btnPagar" class="btn btn-primary btn-block btn-lg" data-pedido-id="{{ pedido.id }}">Pagar</a>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        const paymentMethodSelect = document.getElementById('paymentMethod');
        const btnPagar = document.getElementById('btnPagar');
        let selectedPaymentMethod = paymentMethodSelect.value;

        paymentMethodSelect.addEventListener('change', function () {
            selectedPaymentMethod = paymentMethodSelect.value;
        });

        btnPagar.addEventListener('click', function () {
            // Obtenha o ID do pedido do atributo data do botão
            const pedidoId = btnPagar.getAttribute('data-pedido-id');

            switch (selectedPaymentMethod) {
                case '1':
                    // Construa a URL com o ID do pedido e o método de pagamento e redirecione para o método de pagamento Pix
                    window.location.href = '{% url "pagamento:inicio" pk=0 %}?metodo_pagamento=Pix'.replace('0', pedidoId);
                    break;
                case '2':
                    // Construa a URL com o ID do pedido e o método de pagamento e redirecione para o método de pagamento Boleto
                    window.location.href = '{% url "pagamento:inicio" pk=0 %}?metodo_pagamento=Boleto'.replace('0', pedidoId);
                    break;
                default:
                    // Redirecione para a página de início do pagamento com o método de pagamento padrão (Cartão de crédito)
                    window.location.href = '{% url "pagamento:inicio" pk=0 %}?metodo_pagamento=Cartao'.replace('0', pedidoId);
                    break;
            }
        });
    });
</script>


{% endblock %}